services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./caddy/:/etc/caddy/

  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build:
      context: ./images/Backend
      dockerfile: Dockerfile
    depends_on:
      - database
      - relay
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      DKIM_DOMAIN: ${DKIM_DOMAIN}
      DKIM_SELECTOR: ${DKIM_SELECTOR}
      DKIM_PRIVATE_KEY: ${DKIM_PRIVATE_KEY}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000/blindflare/hello || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  relay:
    build:
      context: ./images/Relay
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "25:25"
    volumes:
      - ./certificates:/app/certificates
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RELAY_CERTIFICATES: ${RELAY_CERTIFICATES}
      RELAY_PRIVATE_KEY: ${RELAY_PRIVATE_KEY}

  tor:
    image: osminogin/tor-simple:latest
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./Tor/torrc:/etc/tor/torrc:ro
      - tor_data:/var/lib/tor

volumes:
  pgdata:
  tor_data: